import type * as schemaType from "./schema";
import { defineSeed } from "void/seed";

export const SEED_EVENTS = [
  {
    id: "dc26-001",
    title: "Mystical Multi Vitamins, Supplements and Mermaids",
    description: "Deep dive into oceanic mythologies, herbal supplement legends, and fantasy creature lore with authors and biologists.",
    location: "Courtland Pool",
    track: "FANTASY LITERATURE",
    startsAt: "2026-09-05T10:00:00Z",
    endsAt: "2026-09-05T11:00:00Z",
    durationMinutes: 60,
    day: "Sat",
    timeString: "10:00 AM - 11:00 AM",
    speakers: "Dr. Coral Vance, Maya Lindqvist",
    contentHash: "hash-001",
  },
  {
    id: "dc26-002",
    title: "The Ultimate Showdown Of Ultimate Destiny",
    description: "Celebrating classic 2000s flash animation, internet folklore, and viral meme culture with veteran animators.",
    location: "Marriott Atrium Ballroom",
    track: "ANIMATION",
    startsAt: "2026-09-05T10:00:00Z",
    endsAt: "2026-09-05T11:30:00Z",
    durationMinutes: 90,
    day: "Sat",
    timeString: "10:00 AM - 11:30 AM",
    speakers: "Neil C., Shawn B., Elena Rostova",
    contentHash: "hash-002",
  },
  {
    id: "dc26-003",
    title: "Hot Dog Costume Contest",
    description: "Who wore the bun best? Annual fan-favorite parade and craftsmanship judging of hot dog themed cosplay masterpieces.",
    location: "Fandangles",
    track: "COSTUMING",
    startsAt: "2026-09-05T11:00:00Z",
    endsAt: "2026-09-05T12:00:00Z",
    durationMinutes: 60,
    day: "Sat",
    timeString: "11:00 AM - 12:00 PM",
    speakers: "Frank Weener, Mustard Queen",
    contentHash: "hash-003",
  },
  {
    id: "dc26-004",
    title: "Kazoo Notation for Opera",
    description: "Learn how to transpose classic Puccini and Wagner arias for the mighty brass humming horn.",
    location: "Westin Chastain",
    track: "MAIN PROGRAMMING",
    startsAt: "2026-09-05T14:00:00Z",
    endsAt: "2026-09-05T15:00:00Z",
    durationMinutes: 60,
    day: "Sat",
    timeString: "2:00 PM - 3:00 PM",
    speakers: "Maestro Buzz, Sarah Jenkins",
    contentHash: "hash-004",
  },
  {
    id: "dc26-005",
    title: "The Monsterotica Manual",
    description: "Tropes, biology, and sociological trends in creature fiction and speculative romance.",
    location: "Hilton 301",
    track: "SCIENCE",
    startsAt: "2026-09-05T16:00:00Z",
    endsAt: "2026-09-05T17:00:00Z",
    durationMinutes: 60,
    day: "Sat",
    timeString: "4:00 PM - 5:00 PM",
    speakers: "G. R. Finch, Lyra Valentine",
    contentHash: "hash-005",
  },
  {
    id: "dc26-006",
    title: "Dragon Con: Not A Dating Site",
    description: "Stories, etiquette, friendship-building, and late-night con survival tips from veterans of 20+ conventions.",
    location: "Hyatt Centennial I",
    track: "MAIN PROGRAMMING",
    startsAt: "2026-09-05T22:30:00Z",
    endsAt: "2026-09-05T23:30:00Z",
    durationMinutes: 60,
    day: "Sat",
    timeString: "10:30 PM - 11:30 PM",
    speakers: "DJ Dragon, Captain Con",
    contentHash: "hash-006",
  },
  {
    id: "dc26-007",
    title: "Cyberpunk Worldbuilding in 2026",
    description: "From neural interfaces to smart cities: how sci-fi predicted reality and where speculative fiction goes next.",
    location: "Sheraton Grand Ballroom",
    track: "SCI-FI LIT",
    startsAt: "2026-09-04T13:00:00Z",
    endsAt: "2026-09-04T14:00:00Z",
    durationMinutes: 60,
    day: "Fri",
    timeString: "1:00 PM - 2:00 PM",
    speakers: "K. Gibson, Ren Vance",
    contentHash: "hash-007",
  },
  {
    id: "dc26-008",
    title: "Atlanta Skybridges & Con-Floor Navigation",
    description: "The official tactical guide to avoiding humidity, navigating skybridges, and estimating walk times between hotels.",
    location: "Marriott Imperial Ballroom",
    track: "MAIN PROGRAMMING",
    startsAt: "2026-09-03T18:00:00Z",
    endsAt: "2026-09-03T19:00:00Z",
    durationMinutes: 60,
    day: "Thu",
    timeString: "6:00 PM - 7:00 PM",
    speakers: "Skybridge Master, Transit Team",
    contentHash: "hash-008",
  },
];

export default defineSeed<typeof schemaType>(async ({ db, schema }) => {
  await db.insert(schema.events).values(SEED_EVENTS);
  await db.insert(schema.eventChanges).values([
    {
      eventId: "dc26-003",
      eventTitle: "Hot Dog Costume Contest",
      changeType: "ROOM_CHANGE",
      diffDetails: "Moved from Courtland to Fandangles",
    },
    {
      eventId: "dc26-004",
      eventTitle: "Kazoo Notation for Opera",
      changeType: "TIME_CHANGE",
      diffDetails: "Pushed by 30 mins to 2:00 PM",
    },
  ]);
});
